replicaCount: 1
appName: project-mgmt

image:
  repository: "harbor.pezl.local/project_mgmt/nestjs-project-service"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  rewriteTarget: /api/v1/$2
  tls:
    secretName: project-mgmt-tls
    hosts: project-mgmt.pezl.local
  host: project-mgmt.pezl.local
  paths: /api/v1/(projects|project_members)(/|$)(.*)
  pathType: ImplementationSpecific

existingEnv: auth-mgmt-env